[versions]
agp = "9.4.0"
appcompat = "1.8.0"
constraintlayout = "2.2.2"
material = "1.14.0"
activity = "1.13.0"
vectordrawable = "1.2.0"
coreKtx = "1.19.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vectordrawable" }
androidx-vectordrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "vectordrawable" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }